### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by TheCuteOwl** [Mehran1022mm/PasswordGenerator#1]
Hi ui check your code yes there is no virus and that's cool but not everyone will check, Can i requests you to remove the obfuscation.

**Comment by 0Magenta0** [comment]
> Hi ui check your code yes there is no virus and that's cool but not everyone will check, Can i requests you to remove the obfuscation.

This obfuscation is as stupid as the python code itself and its author.
Source:
```python
# Packages

import os
import time
import random
import colorama
import clipboard
import pyperclip
from colorama import Fore
colorama.init(True)


print(\'\')
# Things

prefix = f"{colorama.Fore.RED}[UltraPW] "
white = f"{colorama.Fore.WHITE}"
yellow = f"{colorama.Fore.YELLOW}"
lenght_limit = 33
lower = "abcdefghijklmnopqrstuvwxyz"
upper =  "ABCDEFGHIGKLMNOPQRSTUVWXYZ"
number = "0123456789"
symbol = "!@#$%&*()."
Combine = lower + upper + number + symbol

# Design

os.system(\'\')
print(f"""{colorama.Fore.RED}




 \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\
 \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\
 \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x9d\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x95\x9a\xe2\
 \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\
 \xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x88\xe2\
 \xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x95\x9a\xe2\
        """)
print("")
print(white + f"Password Generator 1.0 {Fore.GREEN}BETA{Fore.WHITE} Made By Mehran1022")
print("")
input("Press Enter To Countinue...")
print("")
passcode = int(input(prefix + white + "Your Password Length: "))
print(prefix + white + "Generating...")
time.sleep(2.5)
password = "".join(random.sample(Combine, passcode))

# Generation Options

if lenght_limit > passcode:
  print(prefix + white +"Your Password Is " + yellow + password)
  print(\'\')
  time.sleep(1.5)
  copy = str(input(prefix + white + "Copy The Password Into Clipboard (y/n): "))
  if copy == \'y\' or copy == \'yes\':
    clipboard.copy(password)
    time.sleep(1)
    print(prefix + white + "Copied Successfully")
  else:
    print(prefix + white + "Terminatig Tasks.")

else:
    print(prefix + white + "You Cannot Enter Numbers Higher Than 32.")

# Program Loop

#print("")
# end = str(input(prefix + white + "Close The App? : "))
#if end == "yes" or end == "y" or end == "Y":
#  code()
# if end == \'n\' or end == \'no\':
#  print(prefix + white + "Terminating The Script...")
```

**Comment by TheCuteOwl** [comment]
this
# Packages

import os
import time
import random
import colorama
import clipboard
import pyperclip
from colorama import Fore
colorama.init(True)


print('')
# Things

prefix = f"{colorama.Fore.RED}[UltraPW] "
white = f"{colorama.Fore.WHITE}"
yellow = f"{colorama.Fore.YELLOW}"
lenght_limit = 33
lower = "abcdefghijklmnopqrstuvwxyz"
upper =  "ABCDEFGHIGKLMNOPQRSTUVWXYZ"
number = "0123456789"
symbol = "!@#$%&*()."
Combine = lower + upper + number + symbol

# Design

os.system('')
print(f"""{colorama.Fore.RED}
        
        
        

 ██████╗░░█████╗░░██████╗░██████╗░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░
 ██╔══██╗██╔══██╗██╔════╝██╔════╝░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗
 ██████╔╝███████║╚█████╗░╚█████╗░░╚██╗████╗██╔╝██║░░██║██████╔╝██║░░██║
 ██╔═══╝░██╔══██║░╚═══██╗░╚═══██╗░░████╔═████║░██║░░██║██╔══██╗██║░░██║
 ██║░░░░░██║░░██║██████╔╝██████╔╝░░╚██╔╝░╚██╔╝░╚█████╔╝██║░░██║██████╔╝
 ╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚═════╝░░░░╚═╝░░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚═════╝░
        """)
print("")
print(white + f"Password Generator 1.0 {Fore.GREEN}BETA{Fore.WHITE} Made By Mehran1022")
print("")
input("Press Enter To Countinue...")
print("")
passcode = int(input(prefix + white + "Your Password Length: "))
print(prefix + white + "Generating...")
time.sleep(2.5)
password = "".join(random.sample(Combine, passcode))

# Generation Options

if lenght_limit > passcode:
  print(prefix + white +"Your Password Is " + yellow + password)
  print('')
  time.sleep(1.5)
  copy = str(input(prefix + white + "Copy The Password Into Clipboard (y/n): "))
  if copy == 'y' or copy == 'yes':
    clipboard.copy(password)
    time.sleep(1)
    print(prefix + white + "Copied Successfully")
  else:
    print(prefix + white + "Terminatig Tasks.")
    
else:
    print(prefix + white + "You Cannot Enter Numbers Higher Than 32.")

# Program Loop

#print("")
# end = str(input(prefix + white + "Close The App? : "))
#if end == "yes" or end == "y" or end == "Y":
#  code()
# if end == 'n' or end == 'no':
#  print(prefix + white + "Terminating The Script...")

**Comment by TheCuteOwl** [comment]
```


# Packages

import os
import time
import random
import colorama
import clipboard
import pyperclip
from colorama import Fore
colorama.init(True)


print('')
# Things

prefix = f"{colorama.Fore.RED}[UltraPW] "
white = f"{colorama.Fore.WHITE}"
yellow = f"{colorama.Fore.YELLOW}"
lenght_limit = 33
lower = "abcdefghijklmnopqrstuvwxyz"
upper =  "ABCDEFGHIGKLMNOPQRSTUVWXYZ"
number = "0123456789"
symbol = "!@#$%&*()."
Combine = lower + upper + number + symbol

# Design

os.system('')
print(f"""{colorama.Fore.RED}
        
        
        

 ██████╗░░█████╗░░██████╗░██████╗░██╗░░░░░░░██╗░█████╗░██████╗░██████╗░
 ██╔══██╗██╔══██╗██╔════╝██╔════╝░██║░░██╗░░██║██╔══██╗██╔══██╗██╔══██╗
 ██████╔╝███████║╚█████╗░╚█████╗░░╚██╗████╗██╔╝██║░░██║██████╔╝██║░░██║
 ██╔═══╝░██╔══██║░╚═══██╗░╚═══██╗░░████╔═████║░██║░░██║██╔══██╗██║░░██║
 ██║░░░░░██║░░██║██████╔╝██████╔╝░░╚██╔╝░╚██╔╝░╚█████╔╝██║░░██║██████╔╝
 ╚═╝░░░░░╚═╝░░╚═╝╚═════╝░╚═════╝░░░░╚═╝░░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚═════╝░
        """)
print("")
print(white + f"Password Generator 1.0 {Fore.GREEN}BETA{Fore.WHITE} Made By Mehran1022")
print("")
input("Press Enter To Countinue...")
print("")
passcode = int(input(prefix + white + "Your Password Length: "))
print(prefix + white + "Generating...")
time.sleep(2.5)
password = "".join(random.sample(Combine, passcode))

# Generation Options

if lenght_limit > passcode:
  print(prefix + white +"Your Password Is " + yellow + password)
  print('')
  time.sleep(1.5)
  copy = str(input(prefix + white + "Copy The Password Into Clipboard (y/n): "))
  if copy == 'y' or copy == 'yes':
    clipboard.copy(password)
    time.sleep(1)
    print(prefix + white + "Copied Successfully")
  else:
    print(prefix + white + "Terminatig Tasks.")
    
else:
    print(prefix + white + "You Cannot Enter Numbers Higher Than 32.")

# Program Loop

#print("")
# end = str(input(prefix + white + "Close The App? : "))
#if end == "yes" or end == "y" or end == "Y":
#  code()
# if end == 'n' or end == 'no':
#  print(prefix + white + "Terminating The Script...")
```

**Comment by 0Magenta0** [comment]
It's can be easy decoded with `echo -e`.
>  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x9d\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x95\x9a\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x88\xe2\
>  \xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x95\x9a\xe2\

**Comment by 0Magenta0** [comment]
If you want to generate a password you can just use `openssl` for example.

**Comment by Mehran1022mm** [comment]
> Hi ui check your code yes there is no virus and that's cool but not everyone will check, Can i requests you to remove the obfuscation.

Hi my friend. Thanks for using my stupid script i will remove the obfuscation. I'll be happy if you gimme a star

**Comment by Mehran1022mm** [comment]
> > Hi ui check your code yes there is no virus and that's cool but not everyone will check, Can i requests you to remove the obfuscation.
> 
> This obfuscation is as stupid as the python code itself and its author. Source:
> 
> ```python
> # Packages
> 
> import os
> import time
> import random
> import colorama
> import clipboard
> import pyperclip
> from colorama import Fore
> colorama.init(True)
> 
> 
> print(\'\')
> # Things
> 
> prefix = f"{colorama.Fore.RED}[UltraPW] "
> white = f"{colorama.Fore.WHITE}"
> yellow = f"{colorama.Fore.YELLOW}"
> lenght_limit = 33
> lower = "abcdefghijklmnopqrstuvwxyz"
> upper =  "ABCDEFGHIGKLMNOPQRSTUVWXYZ"
> number = "0123456789"
> symbol = "!@#$%&*()."
> Combine = lower + upper + number + symbol
> 
> # Design
> 
> os.system(\'\')
> print(f"""{colorama.Fore.RED}
> 
> 
> 
> 
>  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x9d\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x95\x9a\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\
>  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x88\xe2\
>  \xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x95\x9a\xe2\
>         """)
> print("")
> print(white + f"Password Generator 1.0 {Fore.GREEN}BETA{Fore.WHITE} Made By Mehran1022")
> print("")
> input("Press Enter To Countinue...")
> print("")
> passcode = int(input(prefix + white + "Your Password Length: "))
> print(prefix + white + "Generating...")
> time.sleep(2.5)
> password = "".join(random.sample(Combine, passcode))
> 
> # Generation Options
> 
> if lenght_limit > passcode:
>   print(prefix + white +"Your Password Is " + yellow + password)
>   print(\'\')
>   time.sleep(1.5)
>   copy = str(input(prefix + white + "Copy The Password Into Clipboard (y/n): "))
>   if copy == \'y\' or copy == \'yes\':
>     clipboard.copy(password)
>     time.sleep(1)
>     print(prefix + white + "Copied Successfully")
>   else:
>     print(prefix + white + "Terminatig Tasks.")
> 
> else:
>     print(prefix + white + "You Cannot Enter Numbers Higher Than 32.")
> 
> # Program Loop
> 
> #print("")
> # end = str(input(prefix + white + "Close The App? : "))
> #if end == "yes" or end == "y" or end == "Y":
> #  code()
> # if end == \'n\' or end == \'no\':
> #  print(prefix + white + "Terminating The Script...")
> ```

deobfuscation fail lmao.

**Comment by 0Magenta0** [comment]
> > > Hi ui check your code yes there is no virus and that's cool but not everyone will check, Can i requests you to remove the obfuscation.
> > 
> > 
> > This obfuscation is as stupid as the python code itself and its author. Source:
> > ```python
> > # Packages
> > 
> > import os
> > import time
> > import random
> > import colorama
> > import clipboard
> > import pyperclip
> > from colorama import Fore
> > colorama.init(True)
> > 
> > 
> > print(\'\')
> > # Things
> > 
> > prefix = f"{colorama.Fore.RED}[UltraPW] "
> > white = f"{colorama.Fore.WHITE}"
> > yellow = f"{colorama.Fore.YELLOW}"
> > lenght_limit = 33
> > lower = "abcdefghijklmnopqrstuvwxyz"
> > upper =  "ABCDEFGHIGKLMNOPQRSTUVWXYZ"
> > number = "0123456789"
> > symbol = "!@#$%&*()."
> > Combine = lower + upper + number + symbol
> > 
> > # Design
> > 
> > os.system(\'\')
> > print(f"""{colorama.Fore.RED}
> > 
> > 
> > 
> > 
> >  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x91\xe2\x96\x91\xe2\
> >  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x97\xe2\x96\x88\xe2\
> >  \xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x9d\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x95\x9a\xe2\
> >  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x94\xe2\x95\x90\xe2\x95\x90\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\
> >  \xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x88\xe2\x96\x88\xe2\x95\x91\xe2\x96\x88\xe2\
> >  \xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x96\x91\xe2\x96\x91\xe2\x95\x9a\xe2\x95\x90\xe2\x95\x9d\xe2\x95\x9a\xe2\
> >         """)
> > print("")
> > print(white + f"Password Generator 1.0 {Fore.GREEN}BETA{Fore.WHITE} Made By Mehran1022")
> > print("")
> > input("Press Enter To Countinue...")
> > print("")
> > passcode = int(input(prefix + white + "Your Password Length: "))
> > print(prefix + white + "Generating...")
> > time.sleep(2.5)
> > password = "".join(random.sample(Combine, passcode))
> > 
> > # Generation Options
> > 
> > if lenght_limit > passcode:
> >   print(prefix + white +"Your Password Is " + yellow + password)
> >   print(\'\')
> >   time.sleep(1.5)
> >   copy = str(input(prefix + white + "Copy The Password Into Clipboard (y/n): "))
> >   if copy == \'y\' or copy == \'yes\':
> >     clipboard.copy(password)
> >     time.sleep(1)
> >     print(prefix + white + "Copied Successfully")
> >   else:
> >     print(prefix + white + "Terminatig Tasks.")
> > 
> > else:
> >     print(prefix + white + "You Cannot Enter Numbers Higher Than 32.")
> > 
> > # Program Loop
> > 
> > #print("")
> > # end = str(input(prefix + white + "Close The App? : "))
> > #if end == "yes" or end == "y" or end == "Y":
> > #  code()
> > # if end == \'n\' or end == \'no\':
> > #  print(prefix + white + "Terminating The Script...")
> > ```
> 
> deobfuscation fail lmao.

Where lmao?
